### ISSUE TITLE
版本

### ISSUE THREAD

**Issue by RichY0608** [FeletexGee/xuexitong_auto_input#1]
还能正常使用不

**Comment by FeletexGee** [comment]
抱歉才看到。

可以的，这个脚本非常简单且本身并不依赖于学习通API支持，甚至没有利用任何前端技术。

请在下次提问前，**认真阅读**[《提问的智慧》](https://github.com/tvvocold/How-To-Ask-Questions-The-Smart-Way)。谢谢。
